title: "ECE 382N: Security at the Hardware-Software Interface"
description: "Course website for \"ECE382N: Security at the Hardware-Software Interface\" at UT Austin"
theme: just-the-docs

url: https://ece382n-sec-ut.github.io

aux_links:
  Home: /

# sass:
#   style: compressed

# include:
#   - assets/css
